#!/bin/sh

CONF="${1}"

KEYREAD=keyread
SCRIPTDIR=/etc/triggerhappy/
VERBOSE=1

[ -e "$CONF" ] && . "$CONF"

$KEYREAD | while read TYPE KEY VALUE; do
    # if the keyread program sends us a keystate, we save it
    # for later
    [ "$TYPE" = "STATE" ] && KEYSTATE="$KEY"
    # we only handle key presses from here on
    [ "$TYPE" = "EV_KEY" -a "$VALUE" = "1" ] || continue;
    
    # export KEYSTATE to the scripts
    export KEYSTATE
    
    SCRIPT="$SCRIPTDIR/$KEY"
    [ $VERBOSE -gt 0 ] && echo "Searching for $SCRIPT"
    [ -f "$SCRIPT" -a -x "$SCRIPT" ] && {
        [ $VERBOSE -gt 0 ] && echo "Launching $SCRIPT..."
        "$SCRIPT" "$TYPE" "$KEY" "$VALUE" &
    }
    [ -d "$SCRIPT" ] && {
        for PROG in "$SCRIPT/*"; do
            [ -f "$PROG" -a -x "$PROG" ] && {
                "$PROG" "$TYPE" "$KEY" "$VALUE" &
            }
        done
    }
done
